### PR TITLE
Add support for PostgreSQL v15.1

### PR DESCRIPTION
**Pull request by satrapu**

### CODE REVIEW

**Comment by mloskot** [comment]
Hi, apologies for using the PR comment, but the issues seem to be disabled.

Is this a known issue?

```
PS> docker run  --rm satrapu/postgresql:15.1-windows
2023-08-08 08:20:54.126 GMT [1352] LOG:  starting PostgreSQL 15.1, compiled by Visual C++ build 1914, 64-bit
2023-08-08 08:20:54.127 GMT [1352] LOG:  listening on IPv6 address "::", port 5432
2023-08-08 08:20:54.128 GMT [1352] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-08-08 08:20:54.334 GMT [1592] LOG:  database system was shut down at 2022-12-02 21:21:48 GMT
2023-08-08 08:20:54.396 GMT [1352] LOG:  database system is ready to accept connections
2023-08-08 08:20:58.878 GMT [1808] FATAL:  database "ContainerUser" does not exist
2023-08-08 08:21:04.039 GMT [1872] FATAL:  database "ContainerUser" does not exist
2023-08-08 08:21:09.194 GMT [1936] FATAL:  database "ContainerUser" does not exist
2023-08-08 08:21:14.353 GMT [1996] FATAL:  database "ContainerUser" does not exist
...
```

I deliberately tried without external volume for `PGDATA` as that requires mounting it with auxiliary container, copying of the configuration files (not mentioned in the current [README.md](https://github.com/satrapu/postgresql-docker-images/blob/576efcb6b2d8762ade5127079447731c7cb17ec3/postgresql/README.md)), then it can be mounted by this container.

**Comment by satrapu** [comment]
Hello @mloskot,

I have tried replicate the issue, but I'm getting a different error:
__docker: a Windows version 10.0.20348-based image is incompatible with a 10.0.19045 host.__
I definitively need to take a closer look.

**Comment by satrapu** [comment]
@mloskot,  
I have enabled issues, so feel free to create one.

**Comment by mloskot** [comment]
@satrapu 
> I have enabled issues, so feel free to create one.

Thanks, done https://github.com/satrapu/postgresql-docker-images/issues/4

> I'm getting a different error: **docker: a Windows version 10.0.20348-based image is incompatible with a 10.0.19045 host.**

That is due to attempt to run container from image based on Windows Server 2022 (10.0.20348 aka `ltsc2022`) on host system with Windows 10 (10.0.19045), unless Hyper-V isolation is used, see https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility

**Pull request merged**
